[package]
name = "EvilDNS"
version = "0.1.0"
authors = ["Raghu Saxena <poiasdpoiasd@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
